/*
 * Copyright (C) 2010 Francisco José Morero Peyrona. All Rights Reserved.
 *
 * This file is part of Tapas project: http://code.google.com/p/tapas-tpv/
 *
 * GNU Classpath is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the free
 * Software Foundation; either version 3, or (at your option) any later version.
 *
 * Tapas is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Tapas; see the file COPYING.  If not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package com.peyrona.tapas.office;

import com.peyrona.tapas.persistence.Configuration;
import com.peyrona.tapas.persistence.DataProvider;
import com.peyrona.tapas.swing.SwingUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 *
 * @author peyrona
 */
class Basic extends javax.swing.JPanel implements ActionListener
{
    private Configuration config;

    /** Creates new form Basic */
    Basic( Configuration config )
    {
        this.config = config;

        initComponents();

        txtEmail.setText( config.getEmail() );
        txtPassword.setText( config.getPassword() );
        txtMusicFolder.setText( config.getMusicFolder() );
        chkFullScreen.setSelected( config.isFullScreenSelected() );
        chkAutoAlign.setSelected( config.isAutoAlignSelected() );
    }

    //------------------------------------------------------------------------//

    // Este método es llamado cuando se va a cerrar la dialog
    @Override
    public void actionPerformed( ActionEvent e )
    {
        boolean bFullScr   = chkFullScreen.isSelected();
        boolean bAutoAlign = chkAutoAlign.isSelected();
        String  sPassword  = txtPassword.getText();
        char[]  acPassword = null;
        String  sEmail     = txtEmail.getText();
        String  sMusicDir  = txtMusicFolder.getText();

        if( sPassword != null  )
            acPassword = sPassword.trim().toCharArray();

        config.setEmail( sEmail );
        config.setPassword( acPassword );
        config.setMusicFolder( sMusicDir );
        config.setFullScreenMode( bFullScr );
        config.setAutoAlignMode( bAutoAlign );

        DataProvider.getInstance().setConfiguration( config );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        chkFullScreen = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        chkAutoAlign = new javax.swing.JCheckBox();
        lblMusicFolder = new javax.swing.JLabel();
        txtMusicFolder = new javax.swing.JTextField();
        btnSelectFolder = new javax.swing.JButton();

        lblPassword.setText("Contraseña administrativa");

        chkFullScreen.setText("Utilizar toda la pantalla para la aplicación");

        lblEmail.setText("email (enviar diario de caja)");

        chkAutoAlign.setText("Alinear automáticamente las cuentas");

        lblMusicFolder.setText("Carpeta base de música");

        btnSelectFolder.setText("...");
        btnSelectFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSelectFolder(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAutoAlign)
                    .addComponent(chkFullScreen)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblPassword)
                            .addComponent(lblMusicFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtMusicFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelectFolder)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMusicFolder)
                    .addComponent(txtMusicFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectFolder))
                .addGap(18, 18, 18)
                .addComponent(chkFullScreen)
                .addGap(18, 18, 18)
                .addComponent(chkAutoAlign)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onSelectFolder(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onSelectFolder
    {//GEN-HEADEREND:event_onSelectFolder
        File folder = SwingUtils.folderChooser();

        if( folder != null )
            txtMusicFolder.setText( folder.getAbsolutePath() );
    }//GEN-LAST:event_onSelectFolder

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectFolder;
    private javax.swing.JCheckBox chkAutoAlign;
    private javax.swing.JCheckBox chkFullScreen;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMusicFolder;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMusicFolder;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}