/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.peyrona.tapas.player;

import com.peyrona.tapas.Utils;
import javax.swing.ImageIcon;

/**
 * Player: sencillo y simple reproductor de música.
 * Es una JInternalFrame que, una vez creada puede estar visible o no, pero
 * siempre existe, para que este modo, pueda reproducir música en una imitación
 * de "background".<br>
 * El truco consiste en hacerla HIDE_ON_CLOSE.
 *
 * @author peyrona
 */
public class Player extends javax.swing.JInternalFrame
{
    private enum Status { Playing, Paused, Sttoped }

    private static Player instance;

    private PlayList playList;
    private Status   status;

    //------------------------------------------------------------------------//

    public static Player getInstance()
    {
        synchronized( Player.class )
        {
            if( instance == null )
                instance = new Player();
        }

        return instance;
    }

    //------------------------------------------------------------------------//

    private void onPlayPause()
    {
        switch( status )
        {
            case Sttoped:
            case Paused :
                status = Status.Playing;
                btnPlayPause.setIcon( new ImageIcon( getClass().getResource( "images/pause.png" ) ) );
                lblInfo.setText( "El reproductor está reproduciendo música" );
                break;

            case Playing:
                status = Status.Paused;
                btnPlayPause.setIcon( new ImageIcon( getClass().getResource( "images/play.png" ) ) );
                lblInfo.setText( "El reprodutor está en pausa" );
                break;
        }

        btnStop.setSelected( false );
    }

    private void onStop()
    {
        status = Status.Sttoped;
        lblInfo.setText( "El reprodutor está parado" );
    }

    private String onEject()
    {
        return null;
    }

    private void onRandom()
    {

    }

    private void onVolume()
    {

    }

    /** Creates new form Player */
    private Player()
    {
        initComponents();

        String sBaseFolder = "/home/peyrona/Música/Jazz"; // FIXME: leerlo del config

        if( Utils.isEmpty( sBaseFolder ) )
            sBaseFolder = onEject();

        playList = new PlayList( sBaseFolder );
        spTable.setViewportView( playList );
        btnStop.doClick();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEject = new javax.swing.JButton();
        sldVolume = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        btnPlayPause = new javax.swing.JButton();
        btnRandom = new javax.swing.JToggleButton();
        spTable = new javax.swing.JScrollPane();
        btnStop = new javax.swing.JToggleButton();
        lblInfo = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reproductor de música");
        setPreferredSize(new java.awt.Dimension(600, 360));

        btnEject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peyrona/tapas/player/images/eject.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peyrona/tapas/player/images/volume.png"))); // NOI18N

        btnPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peyrona/tapas/player/images/play.png"))); // NOI18N
        btnPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPauseActionPerformed(evt);
            }
        });

        btnRandom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peyrona/tapas/player/images/random.png"))); // NOI18N

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/peyrona/tapas/player/images/stop.png"))); // NOI18N
        btnStop.setSelected(true);

        lblInfo.setText("Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEject, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(sldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEject, btnPlayPause, btnRandom, btnStop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEject, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnRandom, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnPlayPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sldVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addComponent(btnStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayPauseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlayPauseActionPerformed
    {//GEN-HEADEREND:event_btnPlayPauseActionPerformed
        onPlayPause();
    }//GEN-LAST:event_btnPlayPauseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEject;
    private javax.swing.JButton btnPlayPause;
    private javax.swing.JToggleButton btnRandom;
    private javax.swing.JToggleButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JSlider sldVolume;
    private javax.swing.JScrollPane spTable;
    // End of variables declaration//GEN-END:variables
}